services:
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: notro-challenge-api

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: notro-challenge-front
    depends_on:
      - api